spring.application.name=localsearch
spring.datasource.url=jdbc:postgresql://localhost:5432/ramblealot_db
spring.datasource.username=postgres
spring.datasource.password=1234qwer
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
